### ISSUE TITLE
As a admin I want to be able to view the details of an issue, so I can decide my next step

### ISSUE THREAD

**Issue by Reinoptland** [luizfiorentino/my-city-app#2]
# Why

- In the future issues are expected to have many more details like uploaded images etc
- This will not fit in the current overview UI
- Also, admins will be able to update issues in various ways, we need room in the UI for this as well
- That's why it's good for each issue to have separate page

## What

- A details page displaying the current details for the issue (for now)

## How

- [x] create a details page for each issue in the route `/admin/issues/[issueId].js`
- [x] load the issue using `getServerProps`
- [x] Styling for mobile
- [x] Styling for tablet / desktop

![Image](https://user-images.githubusercontent.com/20372832/230014508-1077a7c7-8d27-43c0-b6a1-477e282fb70e.png)

![Image](https://user-images.githubusercontent.com/20372832/230014609-1046b074-1d29-4c81-b11b-b0e41dcb1617.png)

**Comment by luizfiorentino** [comment]
Hey Rein, think the feature is implemented, please check out the demo video:

![Video](https://share.getcloudapp.com/6qubZQJj)

**Comment by luizfiorentino** [comment]
Hey Rein, think the feature is implemented, please check out the demo video:

https://share.getcloudapp.com/6qubZQJj

**Comment by Reinoptland** [comment]
Done! You can push, PR & merge it (maybe wth small changes from the video?)
